.TH "MQTTAsync_interface::MQTTAsync_addresses" 3 "Sun Dec 22 2024 18:56:25" "Paho Asynchronous MQTT C Client Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MQTTAsync_interface::MQTTAsync_addresses
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MQTTAsync\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfamily\fP"
.br
.ti -1c
.RI "char * \fBaddress\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int family"
the internet family of this address, AF_INET or AF_INET6 
.SS "char* address"
the printable representation of the address 

.SH "Author"
.PP 
Generated automatically by Doxygen for Paho Asynchronous MQTT C Client Library from the source code\&.
