.TH "MQTTClient_interface" 3 "Sun Dec 22 2024 18:56:25" "Paho MQTT C Client Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MQTTClient_interface
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <MQTTClient\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBMQTTClient_addresses\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBstruct_id\fP [4]"
.br
.ti -1c
.RI "int \fBstruct_version\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBfamily\fP"
.br
.ti -1c
.RI "int \fBaddress_count\fP"
.br
.ti -1c
.RI "struct \fBMQTTClient_interface::MQTTClient_addresses\fP * \fBaddresses\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char struct_id[4]"

.SS "int struct_version"
The eyecatcher for this structure\&. Must be MQIN\&. 
.SS "char* name"
The version number of this structure\&. Must be 0\&. the interface name, or NULL to ignore 
.SS "int family"
the address family AF_INET or AF_INET6 
.SS "int address_count"
the number of addresses in the address array\&. 0 to ignore 
.SS "struct \fBMQTTClient_interface::MQTTClient_addresses\fP * addresses"
an array of addresses connected to this interface 

.SH "Author"
.PP 
Generated automatically by Doxygen for Paho MQTT C Client Library from the source code\&.
